#!/usr/bin/env python3
"""Copy the code-free research outputs the server needs into data/.

The research repository (private) derives two things from the original
client that are safe to publish: the boot manifest (which archived file to
serve for each URL the target client requests, with SHA-256) and the event
contracts (event names, argument counts and shapes; no original code).
This script reduces them to what the server reads and records where they
came from, so the copies can be regenerated and checked instead of edited.

    python3 scripts/import_research.py --research ../vertix-research [--check]

--check exits 1 if the files in data/ differ from a fresh import.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from urllib.parse import urlsplit

BUILD = "20160806061006"
ROOT = Path(__file__).resolve().parent.parent
OUT_BOOT = ROOT / "data" / "boot" / ("%s.json" % BUILD)
OUT_CONTRACTS = ROOT / "data" / "contracts" / ("%s.json" % BUILD)

# Third-party script URLs the page shell loads. They are served from the
# archive under /cdn/<host>/<path> and the page's references are rewritten to
# match (see src/originals/page.rs).
CDN_HOSTS = {"code.jquery.com", "cdn.socket.io"}


def serve_path(url: str) -> str | None:
    """Map a URL as the client writes it to the path our server answers."""
    parts = urlsplit(url)
    if parts.scheme in ("http", "https"):
        if parts.hostname in CDN_HOSTS:
            return "/cdn/%s%s" % (parts.hostname, parts.path)
        return None
    path = parts.path
    while path.startswith("../") or path.startswith("./"):
        path = path[path.index("/") + 1:]
    return "/" + path.lstrip("/")


def research_commit(research: Path) -> str:
    out = subprocess.run(["git", "-C", str(research), "rev-parse", "HEAD"], capture_output=True, text=True)
    return out.stdout.strip() if out.returncode == 0 else "unknown"


def build_boot(research: Path) -> dict:
    src = research / "analyses" / "out" / "boot" / ("%s.json" % BUILD)
    manifest = json.loads(src.read_text(encoding="utf-8"))
    routes = []
    for entry in manifest["entries"]:
        pick = entry.get("pick")
        if not pick:
            continue
        path = serve_path(entry["url"])
        if path is None:
            continue
        location = pick["location"]
        container, _, member = location.partition("::")
        routes.append({
            "path": path,
            "role": entry.get("role", ""),
            "source": pick["source"].split(":")[0],
            "archive_path": container,
            "member": member or None,
            "sha256": pick["sha256"],
            "bytes": pick["bytes"],
            "note": entry.get("flag", ""),
        })
    # One route per path; the research manifest lists the favicon twice
    # (page link with ?v=12 and the CSS reference), with the same bytes.
    by_path: dict[str, dict] = {}
    for r in routes:
        prev = by_path.get(r["path"])
        if prev and prev["sha256"] != r["sha256"]:
            raise SystemExit("conflicting picks for %s" % r["path"])
        by_path.setdefault(r["path"], r)
    client = manifest["client"]
    shell = manifest["page_shell"]
    return {
        "note": "Generated by scripts/import_research.py from the research boot manifest. "
                "Paths and hashes only; the files themselves are read from a local archive clone.",
        "build": BUILD,
        "research_commit": research_commit(research),
        "page_shell": {
            "archive_path": shell["chosen"],
            "sha256": shell["sha256"],
            "capture": shell["capture"],
            "why": shell["why"],
        },
        "client": {"archive_path": client["path"], "sha256": client["sha256"]},
        "routes": sorted(by_path.values(), key=lambda r: r["path"]),
    }


def build_contracts(research: Path) -> dict:
    src = research / "analyses" / "out" / "contracts" / "contracts-public.json"
    data = json.loads(src.read_text(encoding="utf-8"))
    build = data["builds"][BUILD]
    events = []
    for c in build["contracts"]:
        counts = c.get("arg_counts") or c.get("param_counts") or []
        events.append({"event": c["event"], "direction": c["direction"], "counts": counts})
    return {
        "note": "Event names and argument counts for the %s client, from the research repository's "
                "code-free contracts (RECOVERED from the client's own handlers and emit sites)." % BUILD,
        "build": BUILD,
        "client_sha256": build["client_sha256"],
        "research_commit": research_commit(research),
        "events": sorted(events, key=lambda e: (e["direction"], e["event"])),
    }


def dump(obj: dict) -> str:
    return json.dumps(obj, indent=2, sort_keys=False) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--research", required=True, type=Path, help="vertix-research checkout")
    ap.add_argument("--check", action="store_true", help="fail if data/ is stale instead of writing")
    args = ap.parse_args(argv)
    outputs = {OUT_BOOT: dump(build_boot(args.research)), OUT_CONTRACTS: dump(build_contracts(args.research))}
    stale = []
    for path, text in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if args.check:
            # research_commit differs between checkouts; compare everything else
            strip = lambda t: "\n".join(ln for ln in (t or "").splitlines() if '"research_commit"' not in ln)  # noqa: E731
            if strip(current) != strip(text):
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print("wrote %s" % path.relative_to(ROOT))
    for p in stale:
        print("stale: %s" % p.relative_to(ROOT))
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
